// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Test.Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
    using global::Avro;
    using global::Avro.Specific;

    public partial class EnumerateDevicesResponse : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""EnumerateDevicesResponse"",""namespace"":""Test.Avro"",""fields"":[{""name"":""devices"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""DeviceProperties"",""namespace"":""Test.Avro"",""fields"":[{""name"":""name"",""type"":""string""},{""name"":""model"",""type"":""string""},{""name"":""vendor"",""type"":""string""},{""name"":""serial_number"",""type"":""string""}]}}}]}");
		private IList<Test.Avro.DeviceProperties> _devices;
		public virtual Schema Schema
		{
			get
			{
				return EnumerateDevicesResponse._SCHEMA;
			}
		}
		public IList<Test.Avro.DeviceProperties> devices
		{
			get
			{
				return this._devices;
			}
			set
			{
				this._devices = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.devices;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.devices = (IList<Test.Avro.DeviceProperties>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
