// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Test.Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
    using global::Avro;
    using global::Avro.Specific;

    public partial class ReserveRequest : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"ReserveRequest\",\"namespace\":\"test.avro\",\"fields\":[{\"name" +
				"\":\"reservation_id\",\"type\":\"string\"},{\"name\":\"client_id\",\"type\":\"string\"}]}");
		private string _reservation_id;
		private string _client_id;
		public virtual Schema Schema
		{
			get
			{
				return ReserveRequest._SCHEMA;
			}
		}
		public string reservation_id
		{
			get
			{
				return this._reservation_id;
			}
			set
			{
				this._reservation_id = value;
			}
		}
		public string client_id
		{
			get
			{
				return this._client_id;
			}
			set
			{
				this._client_id = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.reservation_id;
			case 1: return this.client_id;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.reservation_id = (System.String)fieldValue; break;
			case 1: this.client_id = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
