// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Test.Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
    using global::Avro;
    using global::Avro.Specific;

    public partial class UnreserveResponse : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"UnreserveResponse\",\"namespace\":\"test.avro\",\"fields\":[{\"n" +
				"ame\":\"is_unreserved\",\"type\":\"boolean\"}]}");
		private bool _is_unreserved;
		public virtual Schema Schema
		{
			get
			{
				return UnreserveResponse._SCHEMA;
			}
		}
		public bool is_unreserved
		{
			get
			{
				return this._is_unreserved;
			}
			set
			{
				this._is_unreserved = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.is_unreserved;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.is_unreserved = (System.Boolean)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
