/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class IsReservedByClientResponse : TBase
{
  private bool _is_reserved;

  public bool Is_reserved
  {
    get
    {
      return _is_reserved;
    }
    set
    {
      __isset.is_reserved = true;
      this._is_reserved = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool is_reserved;
  }

  public IsReservedByClientResponse()
  {
  }

  public IsReservedByClientResponse DeepCopy()
  {
    var tmp38 = new IsReservedByClientResponse();
    if(__isset.is_reserved)
    {
      tmp38.Is_reserved = this.Is_reserved;
    }
    tmp38.__isset.is_reserved = this.__isset.is_reserved;
    return tmp38;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Bool)
            {
              Is_reserved = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp39 = new TStruct("IsReservedByClientResponse");
      await oprot.WriteStructBeginAsync(tmp39, cancellationToken);
      var tmp40 = new TField();
      if(__isset.is_reserved)
      {
        tmp40.Name = "is_reserved";
        tmp40.Type = TType.Bool;
        tmp40.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp40, cancellationToken);
        await oprot.WriteBoolAsync(Is_reserved, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is IsReservedByClientResponse other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.is_reserved == other.__isset.is_reserved) && ((!__isset.is_reserved) || (System.Object.Equals(Is_reserved, other.Is_reserved))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.is_reserved)
      {
        hashcode = (hashcode * 397) + Is_reserved.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp41 = new StringBuilder("IsReservedByClientResponse(");
    int tmp42 = 0;
    if(__isset.is_reserved)
    {
      if(0 < tmp42++) { tmp41.Append(", "); }
      tmp41.Append("Is_reserved: ");
      Is_reserved.ToString(tmp41);
    }
    tmp41.Append(')');
    return tmp41.ToString();
  }
}

