/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class ResetServerResponse : TBase
{
  private bool _is_server_reset;

  public bool Is_server_reset
  {
    get
    {
      return _is_server_reset;
    }
    set
    {
      __isset.is_server_reset = true;
      this._is_server_reset = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool is_server_reset;
  }

  public ResetServerResponse()
  {
  }

  public ResetServerResponse DeepCopy()
  {
    var tmp57 = new ResetServerResponse();
    if(__isset.is_server_reset)
    {
      tmp57.Is_server_reset = this.Is_server_reset;
    }
    tmp57.__isset.is_server_reset = this.__isset.is_server_reset;
    return tmp57;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Bool)
            {
              Is_server_reset = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp58 = new TStruct("ResetServerResponse");
      await oprot.WriteStructBeginAsync(tmp58, cancellationToken);
      var tmp59 = new TField();
      if(__isset.is_server_reset)
      {
        tmp59.Name = "is_server_reset";
        tmp59.Type = TType.Bool;
        tmp59.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp59, cancellationToken);
        await oprot.WriteBoolAsync(Is_server_reset, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is ResetServerResponse other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.is_server_reset == other.__isset.is_server_reset) && ((!__isset.is_server_reset) || (System.Object.Equals(Is_server_reset, other.Is_server_reset))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.is_server_reset)
      {
        hashcode = (hashcode * 397) + Is_server_reset.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp60 = new StringBuilder("ResetServerResponse(");
    int tmp61 = 0;
    if(__isset.is_server_reset)
    {
      if(0 < tmp61++) { tmp60.Append(", "); }
      tmp60.Append("Is_server_reset: ");
      Is_server_reset.ToString(tmp60);
    }
    tmp60.Append(')');
    return tmp60.ToString();
  }
}

